#!/bin/bash
set -e

# setting so uneditable markdown cells can't be un-rendered in notebooks
mkdir -p ${CONDA_PREFIX}/share/jupyter/lab/settings

echo '
{
    "@jupyterlab/notebook-extension:tracker": {
        "showEditorForReadOnlyMarkdown" : false}
}
' > ${CONDA_PREFIX}/share/jupyter/lab/settings/overrides.json

exec "$@"
